<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-19 at 18:51:23.
 */
class configOptionsTest
        extends PHPUnit_Framework_TestCase
{

    /**
     * @var configOptions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new configOptions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers configOptions::toJSON
     * @todo   Implement testToJSON().
     */
    public function testToJSON()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configOptions::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configOptions::values
     * @todo   Implement testValues().
     */
    public function testValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configOptions::_valid_int
     * @todo   Implement test_valid_int().
     */
    public function test_valid_int()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configOptions::_valid_int_or_percent
     * @todo   Implement test_valid_int_or_percent().
     */
    public function test_valid_int_or_percent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configOptions::_get_caller
     * @todo   Implement test_get_caller().
     */
    public function test_get_caller()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
